### ISSUE TITLE
Can't run a gii command more than once from my own command

### ISSUE THREAD

**Issue by machour** [yiisoft/yii2-gii#104]
I was writing a console command that would generate all my models crud :

```php
foreach ($models as $model) {
          $this->run("gii/crud", [
                'controllerClass' => 'backend\\controllers\\' . $model . 'Controller',
                'modelClass' => 'common\\models\\' . $model,
                'viewPath' => 'backend/views/' . strtolower($model),
                'enableI18N' => 1,
                'messageCategory' => 'backend',
                'searchModelClass' => 'backend\\search\\' . $model . 'Search',
                'baseControllerClass' => 'backend\\controllers\\Controller',
                'template' => 'adminlte',
                'interactive' => 0
            ]);
}
```

in the second loop, the call fails with the following error:

```
Exception 'yii\base\InvalidConfigException' with message 'Unsupported configuration type: object'

in /private/var/www/flycarrent/vendor/yiisoft/yii2/BaseYii.php:350

Stack trace:
#0 /private/var/www/flycarrent/vendor/yiisoft/yii2-gii/Module.php(117): yii\BaseYii::createObject(Object(yii\gii\generators\model\Generator))
#1 /private/var/www/flycarrent/vendor/yiisoft/yii2/base/Controller.php(139): yii\gii\Module->beforeAction(Object(yii\gii\console\GenerateAction))
#2 /private/var/www/flycarrent/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('crud', Array)
#3 /private/var/www/flycarrent/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('crud', Array)
#4 /private/var/www/flycarrent/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('gii/crud', Array)
#5 /private/var/www/flycarrent/vendor/yiisoft/yii2/base/Controller.php(183): yii\console\Application->runAction('gii/crud', Array)
#6 /private/var/www/flycarrent/console/controllers/GiiAllController.php(97): yii\base\Controller->run('gii/crud', Array)
#7 [internal function]: console\controllers\GiiAllController->actionIndex()
#8 /private/var/www/flycarrent/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#9 /private/var/www/flycarrent/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#10 /private/var/www/flycarrent/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('', Array)
#11 /private/var/www/flycarrent/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('', Array)
#12 /private/var/www/flycarrent/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('gii-all', Array)
#13 /private/var/www/flycarrent/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('gii-all', Array)
#14 /private/var/www/flycarrent/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#15 /private/var/www/flycarrent/yii(27): yii\base\Application->run()
#16 {main}
```

I pin pointed the problem being located at this line : https://github.com/yiisoft/yii2-gii/blob/master/Module.php#L115
where $this->generators gets overwritten and gets filled with objects instead of configuration arrays.

I think we should add a new private property and keep a copy of the original $generators value in `init()` and reset $generators back to its original value in `resetGlobalSettings()` which is called at the end of `beforeAction()`

**Comment by machour** [comment]
Actually, it should be reset in `afterAction()` instead.
Here's a patch that fixes the issue, but maybe you guys have something cleaner in mind?

```diff
--- a/Module.php
+++ b/Module.php
@@ -66,6 +66,10 @@ class Module extends \yii\base\Module implements BootstrapInterface
      */
     public $generators = [];
     /**
+     * @var array used to make a copy of [[generators]] before altering it in [[beforeAction()]].
+     */
+    private $definedGenerators = [];
+    /**
      * @var integer the permission to be set for newly generated code files.
      * This value will be used by PHP chmod function.
      * Defaults to 0666, meaning the file is read-writable by all users.
@@ -84,6 +88,9 @@ class Module extends \yii\base\Module implements BootstrapInterface
      */
     public function bootstrap($app)
     {
+
+        $this->definedGenerators = $this->generators;
+
         if ($app instanceof \yii\web\Application) {
             $app->getUrlManager()->addRules([
                 $this->id => $this->id . '/default/index',
@@ -122,6 +129,15 @@ class Module extends \yii\base\Module implements BootstrapInterface
     }
 
     /**
+     * @inheritdoc
+     */
+    public function afterAction($action, $result)
+    {
+        $this->generators = $this->definedGenerators;
+        return parent::afterAction($action, $result);
+    }
+
+    /**
      * Resets potentially incompatible global settings done in app config.
      */
     protected function resetGlobalSettings()
```

**Comment by cebe** [comment]
I have made a different fix. Can you check whether that solves your issue?

**Comment by machour** [comment]
it does, thanks!
